[project]
name = "cost_dual"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]

[system-requirements]
linux = "5.4.0"

[tasks]

[dependencies]
polars = ">=1.21.0,<2"
pandas = ">=2.2.3,<3"
numpy = ">=2.2.2,<3"
statsmodels = ">=0.14.4,<0.15"
scipy = ">=1.15.1,<2"
matplotlib = ">=3.10.0,<4"
scikit-learn = ">=1.6.1,<2"
pingouin = ">=0.5.5,<0.6"
pyarrow = ">=19.0.0,<20"
cmdstanpy = ">=1.2.5,<2"
arviz = ">=0.20.0,<0.21"

[pypi-dependencies]

[feature.dev.dependencies]
pytest = ">=8.3.4,<9"
hypothesis = ">=6.126.0,<7"

[environments]
default = { features = ["dev"], solve-group = "prod" }
prod = { features = [], solve-group = "prod" }
